version: '3'
services:
  spark-master:
    image: manh303/spark-test
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "8080:8080"  # Web UI
      - "7077:7077"  # Master port
      - "4040:4040"  # Application UI
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    networks:
      - spark-network

  spark-worker-1:
    image: manh303/spark-test
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_MASTER=spark://spark-master:7077
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-worker-2:
    image: manh303/spark-test
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_MASTER=spark://spark-master:7077
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    depends_on:
      - spark-master
    networks:
      - spark-network
  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: employee
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local